const app=document.getElementById('app');
const images='assets/illustrations/';
const categories={morning:['أذكار الصباح','adhkar-morning.webp'],evening:['أذكار المساء','adhkar-morning.webp'],afterPrayer:['بعد الصلاة','adhkar-morning.webp'],sleeping:['أذكار النوم','adhkar-morning.webp'],wakingUp:['عند الاستيقاظ','adhkar-morning.webp']};
const icons={home:'<svg viewBox="0 0 24 24"><path d="M3.5 10.8 12 3.9l8.5 6.9M5.8 9.7v10.1h12.4V9.7M9.3 19.8v-5.4h5.4v5.4"/></svg>',adhkar:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="7.5" stroke-dasharray="1.2 3"/><path d="M12 4V2.8M12 21.2V20"/></svg>',quran:'<svg viewBox="0 0 24 24"><path d="M4.8 5.2c3.6-.3 5.8.5 7.2 2v12c-1.4-1.5-3.6-2.3-7.2-2zM19.2 5.2c-3.6-.3-5.8.5-7.2 2v12c1.4-1.5 3.6-2.3 7.2-2zM12 7.2v12"/></svg>',listen:'<svg viewBox="0 0 24 24"><path d="M4.5 14v-2a7.5 7.5 0 0 1 15 0v2M3 13.5h2.8v5H3zM18.2 13.5H21v5h-2.8z"/></svg>',more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>'};
const headerIcons={settings:'<svg viewBox="0 0 24 24"><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z"/><path d="m19 13.5 1.3 1-.9 1.6-1.6-.5a7.4 7.4 0 0 1-1.3 1.2l.2 1.7-1.8.6-.8-1.5a7.7 7.7 0 0 1-1.7.2l-.8 1.5-1.8-.6.2-1.7a7.4 7.4 0 0 1-1.3-1.2l-1.6.5-.9-1.6 1.3-1a7.2 7.2 0 0 1 0-1.9l-1.3-1 .9-1.6 1.6.5a7.4 7.4 0 0 1 1.3-1.2l-.2-1.7 1.8-.6.8 1.5a7.7 7.7 0 0 1 1.7-.2l.8-1.5 1.8.6-.2 1.7a7.4 7.4 0 0 1 1.3 1.2l1.6-.5.9 1.6-1.3 1a7.2 7.2 0 0 1 0 1.9Z"/></svg>',listen:'<svg viewBox="0 0 24 24"><path d="M4.5 14v-2a7.5 7.5 0 0 1 15 0v2M3 13.5h2.8v5H3zM18.2 13.5H21v5h-2.8z"/></svg>'};
const labels={home:'الرئيسية',adhkar:'الأذكار',quran:'القرآن',listen:'المسموع',more:'المزيد'};
let chapters=[],verses={},adhkar={},reciters=[],page='home',group=null,chapter=null,query='',audio=new Audio(),playing=false;
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem('nour-'+k))??f}catch{return f}};
const set=(k,v)=>localStorage.setItem('nour-'+k,JSON.stringify(v));
let settings=get('settings',{font:22,theme:'dark'}),bookmark=get('bookmark',{id:1,verse:1}),reciterId=get('reciter','sa-luhaidan-hafs');
let counters=get('counters',{}),tasbih=get('tasbih',0),currentAudio={id:1,name:'الفاتحة'};
const toast=t=>{let el=document.createElement('div');el.className='toast';el.textContent=t;document.body.append(el);setTimeout(()=>el.remove(),2700)};
const title=(t,n='')=>`<div class="section-head"><h2>${t}</h2><span>${n}</span></div>`;
const card=(label,src,action,sub='')=>`<button class="card" style="background-image:linear-gradient(90deg,#0a1726d9,#0a172655),url('${images+src}')" onclick="${action}"><span class="arrow">←</span><h3>${label}</h3><p>${sub}</p></button>`;
function shell(content){document.body.classList.toggle('light',settings.theme==='light');app.innerHTML=`<div class="shell"><header class="topbar"><button class="icon-btn" onclick="navigate('more')" aria-label="الإعدادات">${headerIcons.settings}</button><div class="brand"><img src="assets/logo.png" alt="نور المسلم"><div><h1>نور المسلم</h1><p>بذكر الله تطمئن القلوب</p></div></div><button class="icon-btn" onclick="navigate('listen')" aria-label="المسموع">${headerIcons.listen}</button></header><main>${content}</main></div><nav class="bottom-nav">${Object.keys(labels).map(k=>`<button class="nav-btn ${page===k?'active':''}" onclick="navigate('${k}')"><span class="nav-glyph">${icons[k]}</span><span>${labels[k]}</span></button>`).join('')}</nav>`;}
function home(){let now=new Date();shell(`<section class="hero" style="background-image:linear-gradient(90deg,#05101ded,#05101d40),url('${images}home-hero.webp')"><div><h2>ابدأ يومك بذكر الله</h2><p>القرآن الكريم، الأذكار، وتلاوات تستمع إليها أينما كنت.</p><button class="cta" onclick="navigate('adhkar')">ابدأ أذكارك ←</button></div></section>${title('مرحباً بك',new Intl.DateTimeFormat('ar-LY',{dateStyle:'full'}).format(now))}<section class="panel"><strong>تابع وردك</strong><p class="muted">آخر موضع: سورة ${safe(chapters[bookmark.id-1]?.name||'الفاتحة')}، الآية ${bookmark.verse}</p><button class="cta" onclick="openSurah(${bookmark.id})">متابعة القراءة</button></section>${title('مساحتك اليومية','اختر ما يناسب وقتك')}<section class="cards">${card('أذكار الصباح','adhkar-morning.webp',"openGroup('morning')",'ورد صباحك مع عداد التكرار')}${card('القرآن الكريم','quran-hero.webp',"navigate('quran')",'المصحف كامل دون اتصال')}${card('المسموع','audio-hero.webp',"navigate('listen')",'تلاوات بعدة قراء')}</section>`)}
function adhkarPage(){if(group){const [name,img]=categories[group],list=adhkar[group]||[];shell(`${title(name,`${list.length} أذكار`)}<button class="secondary" onclick="group=null;render()">← جميع الأذكار</button><section class="dhikr-list" style="margin-top:16px">${list.map((d,i)=>{let key=group+'-'+d.id,done=Math.min(counters[key]||0,d.count);return `<article class="dhikr-entry"><div class="dhikr-text">${safe(d.text)}</div><small>${safe(d.reference)} · ${d.count} ${d.count===1?'مرة':'مرات'}</small><button class="secondary" onclick="increment('${key}',${d.count})" ${done>=d.count?'disabled':''}>${done>=d.count?'تم ✓':`${done} / ${d.count} — اضغط للذكر`}</button></article>`}).join('')}</section>`);return}shell(`${title('الأذكار','أوراد مأثورة')}<section class="hero" style="min-height:220px;background-image:linear-gradient(90deg,#05101def,#05101d50),url('${images}adhkar-morning.webp')"><div><h2>أذكار الصباح</h2><p>اقرأ واحتسب التكرار خطوة بخطوة.</p><button class="cta" onclick="openGroup('morning')">ابدأ الآن ←</button></div></section>${title('أقسام الأذكار')}<section class="cards">${Object.entries(categories).map(([id,[name,img]])=>card(name,img,`openGroup('${id}')`,`${adhkar[id]?.length||0} أذكار`)).join('')}</section>`)}
function openGroup(id){group=id;page='adhkar';render();scrollTo(0,0)}
function increment(k,max){counters[k]=Math.min(max,(counters[k]||0)+1);set('counters',counters);render()}
function quranPage(){if(chapter){let data=verses[chapter]||[],c=chapters[chapter-1];shell(`${title('سورة '+safe(c.name),`${data.length} آية`)}<button class="secondary" onclick="chapter=null;render()">← السور</button><section class="reading panel" style="font-size:${settings.font}px">${data.map(v=>`<span class="ayah" id="v${v.verse}">${safe(v.text)} <button title="حفظ موضع القراءة" onclick="saveVerse(${chapter},${v.verse})">۞ ${v.verse}</button></span>`).join('')}</section><div class="reading-actions"><button class="secondary" onclick="playSurah(${chapter})">▶ استمع للسورة</button><button class="secondary" onclick="changeFont(2)">تكبير النص ＋</button><button class="secondary" onclick="changeFont(-2)">تصغير النص −</button></div>`);return}let found=chapters.filter(c=>c.name.includes(query)||String(c.id)===query);shell(`${title('القرآن الكريم','١١٤ سورة • ٦٢٣٦ آية')}<section class="panel reading-panel" style="background-image:linear-gradient(90deg,#081625ee,#08162555),url('${images}quran-hero.webp')"><h3>متابعة القراءة</h3><p>سورة ${safe(chapters[bookmark.id-1]?.name||'الفاتحة')} — الآية ${bookmark.verse}</p><button class="cta" onclick="openSurah(${bookmark.id},${bookmark.verse})">متابعة ←</button></section><div class="search"><input id="search" type="search" placeholder="ابحث عن سورة بالاسم أو الرقم" value="${safe(query)}" oninput="query=this.value;updateSurahs()"></div><div class="surah-list" id="surahs">${surahRows(found)}</div>`)}
function surahRows(list){return list.map(c=>`<button class="surah surah-button" onclick="openSurah(${c.id})"><span class="badge-num">${c.id}</span><span><strong>${safe(c.name)}</strong><small>${c.total_verses} آية • ${c.type==='meccan'?'مكية':'مدنية'}</small></span><span class="gold">←</span></button>`).join('')||'<p class="muted">لا توجد سورة مطابقة.</p>'}
function updateSurahs(){document.getElementById('surahs').innerHTML=surahRows(chapters.filter(c=>c.name.includes(query)||String(c.id)===query))}
function openSurah(id,v){chapter=id;page='quran';render();requestAnimationFrame(()=>{if(v)document.getElementById('v'+v)?.scrollIntoView({block:'center'});else scrollTo(0,0)})}
function saveVerse(id,v){bookmark={id,verse:v};set('bookmark',bookmark);toast('حُفظ موضع القراءة')}
function changeFont(d){settings.font=Math.max(18,Math.min(36,settings.font+d));set('settings',settings);render()}
function audioUrl(id){let r=reciters.find(x=>x.id===reciterId);return r?.server+String(id).padStart(3,'0')+'.mp3'}
function listenPage(){let r=reciters.find(x=>x.id===reciterId);shell(`${title('المسموع','تلاوات القرآن الكريم')}<section class="panel audio-hero" style="background-image:linear-gradient(90deg,#071522ee,#07152266),url('${images}audio-hero.webp')"><div><small>التلاوة الحالية</small><h2>سورة ${safe(chapters[currentAudio.id-1]?.name||'الفاتحة')}</h2><p>${safe(r?.name||'')}</p><button class="cta" onclick="toggleAudio()">${playing?'إيقاف مؤقت Ⅱ':'تشغيل ▶'}</button></div></section><section class="panel" style="margin-top:16px"><label for="reader">اختر القارئ</label><select id="reader" onchange="chooseReciter(this.value)">${reciters.map(x=>`<option value="${safe(x.id)}" ${x.id===reciterId?'selected':''}>${safe(x.name)} — ${safe(x.riwaya)}</option>`).join('')}</select><small class="muted">تُبث التلاوات عبر الإنترنت. قد يختلف نص المصحف المعروض عن رواية القارئ المختارة.</small></section>${title('اختر سورة للاستماع')}<div class="search"><input type="search" placeholder="ابحث عن سورة" value="${safe(query)}" oninput="query=this.value;updateAudioSurahs()"></div><div class="surah-list" id="audio-surahs">${audioRows(chapters.filter(c=>c.name.includes(query)))}</div><section class="panel" style="margin-top:16px"><strong id="audio-status">${playing?'جارٍ التشغيل':'اختر سورة واضغط تشغيل'}</strong><audio id="player" controls preload="none" style="width:100%;margin-top:10px"></audio><p class="muted">للتنزيل، افتح رابط الملف الصوتي من المتصفح: <a id="audio-link" href="${safe(audioUrl(currentAudio.id))}" target="_blank" rel="noopener">ملف التلاوة</a></p></section>`);const el=document.getElementById('player');el.src=audio.src||audioUrl(currentAudio.id);el.currentTime=Number.isFinite(audio.currentTime)?audio.currentTime:0;audio.pause();audio=el;audio.onplay=()=>{playing=true;document.getElementById('audio-status').textContent='جارٍ التشغيل'};audio.onpause=()=>{playing=false;document.getElementById('audio-status').textContent='متوقف مؤقتاً'};audio.onerror=()=>toast('تعذّر تحميل التلاوة. جرّب قارئاً آخر أو تحقق من الإنترنت.');if(playing)audio.play().catch(()=>{playing=false})}
function audioRows(list){return list.map(c=>`<button class="surah surah-button" onclick="playSurah(${c.id})"><span class="badge-num">${c.id}</span><strong>سورة ${safe(c.name)}</strong><span class="gold">▶</span></button>`).join('')||'<p class="muted">لا توجد نتائج.</p>'}
function updateAudioSurahs(){document.getElementById('audio-surahs').innerHTML=audioRows(chapters.filter(c=>c.name.includes(query)))}
function chooseReciter(id){reciterId=id;set('reciter',id);playing=false;audio.pause();audio.removeAttribute('src');listenPage()}
function playSurah(id){currentAudio={id};page='listen';playing=false;audio.pause();audio.removeAttribute('src');query='';listenPage();audio.play().catch(()=>toast('يتطلب التشغيل اتصالاً بالإنترنت أو سماح المتصفح.'))}
function toggleAudio(){if(audio.paused)audio.play().catch(()=>toast('تعذر تشغيل التلاوة'));else audio.pause()}
function morePage(){shell(`${title('المزيد','أدواتك وإعداداتك')}<section class="more-grid"><button class="more-card" onclick="navigate('adhkar')"><span>◌</span><strong>الأذكار</strong></button><button class="more-card" onclick="navigate('quran')"><span>▣</span><strong>ورد القرآن</strong></button></section>${title('المسبحة')}<section class="tasbih"><p>سبحان الله</p><div class="count">${tasbih.toLocaleString('ar-EG')}</div><button class="counter" onclick="tasbih++;set('tasbih',tasbih);morePage()">اضغط للتسبيح</button><div><button class="secondary" onclick="tasbih=0;set('tasbih',0);morePage()">إعادة ضبط العداد</button></div></section>${title('الإعدادات')}<section class="panel settings"><label>المظهر <select onchange="settings.theme=this.value;set('settings',settings);render()"><option value="dark" ${settings.theme==='dark'?'selected':''}>داكن</option><option value="light" ${settings.theme==='light'?'selected':''}>فاتح</option></select></label><label>حجم نص المصحف <input type="range" min="18" max="36" value="${settings.font}" oninput="settings.font=+this.value;set('settings',settings);this.nextElementSibling.textContent=this.value+'px'"><span>${settings.font}px</span></label><p class="muted">التقدم والإعدادات تحفظ على هذا الجهاز. القرآن والأذكار يعملان دون اتصال بعد فتح التطبيق مرة واحدة؛ التلاوات تتطلب اتصالاً.</p></section><p class="muted credits">نص القرآن: Tanzil Project / quran-json، CC BY 3.0. نصوص الأذكار ومراجعها مقتبسة من مشروع زاد المسلم. روابط الصوت: MP3Quran ومصادر القراء المبينة في بيانات المشروع.</p>`)}
function navigate(to){page=to;chapter=null;group=null;query='';history.replaceState(null,'','#'+to);render();scrollTo(0,0)}
function render(){({home,adhkar:adhkarPage,quran:quranPage,listen:listenPage,more:morePage}[page]||home)()}
Promise.all([fetch('quran-data/chapters.json').then(r=>r.json()),fetch('quran-data/uthmani.json').then(r=>r.json()),fetch('adhkar-data.json').then(r=>r.json()),fetch('quran-data/surah-reciters.json').then(r=>r.json())]).then(([c,v,a,r])=>{chapters=c.chapters;verses=v;adhkar=a;reciters=r.reciters;page=['home','adhkar','quran','listen','more'].includes(location.hash.slice(1))?location.hash.slice(1):'home';render()}).catch(()=>{app.innerHTML='<main class="shell"><h1>تعذر تحميل المحتوى</h1><p>أعد فتح التطبيق أو تأكد من اكتمال الملفات.</p></main>'});

if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

